name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./... -o main.exe && zip main.zip main
    - name: Upload output file
      uses: actions/upload-artifact@v2
      with:
        name: main.zip
        path: main.zip
      
    
